### 添加编辑权限
POST http://localhost:8000/user.UserAuth/Edit
Content-Type: application/json

{
    "id":7,
    "pid":1,
    "name":"test"
}

### 获取权限单条数据
POST http://localhost:8000/user.UserAuth/Get
Content-Type: application/json

{
    "name":"admin"
}

### 获取权限列表数据
POST http://localhost:8000/user.UserAuth/List
Content-Type: application/json

{
    "page":1,
    "pageNum":10
}

### 修改单个字段
POST http://localhost:8000/user.UserAuth/Change
Content-Type: application/json

{
    "whereField":"sort",
    "whereVal":20,
    "changeField":"id",
    "changeVal":2
}

### 删除数据
POST http://localhost:8000/user.UserAuth/Del
Content-Type: application/json

{
    "id":1
}