### 添加编辑权限
POST http://localhost:8000/user.UserAuth/Edit
Content-Type: application/json

{
    "id":7,
    "pid":1,
    "name":"test"
}

### 获取权限单条数据
POST http://localhost:8000/user.UserAuth/Get
Content-Type: application/json

{
    "name":"admin"
}

### 获取权限列表数据
POST http://localhost:8000/user.UserAuth/List
Content-Type: application/json

{
    "page":1,
    "pageNum":10
}

### 修改单个字段
POST http://localhost:8000/user.UserAuth/Change
Content-Type: application/json

{
    "whereField":"id",
    "whereVal":20,
    "changeField":"sort",
    "changeVal":2
}

###  
POST http://localhost:8000/api/db.Table/Edit
Content-Type: application/json

{
    "id":1,
    "name":"test2",
    "cname":"测试"
}

### 删除数据
POST http://localhost:8000/api/setting.AdminCate/GetListByPid
Content-Type: application/json

{
   "pid":0
}

### 删除数据
POST https://agentapi.gzshangqi.com/api/WxMerchant/branches
Content-Type: application/json

{
   "bank_alias_code":1000009547,
    "city_code":10
}