### 添加编辑管理员
POST http://localhost:8000/user.User/Edit
Content-Type: application/json

{
    "name":"admin",
    "password":123,
    "duplicatePassword":123
}

### 管理员登录
POST http://localhost:8000/api/user.User/AdminLogin
Content-Type: application/json

{
    "name":"admin",
    "password":"123",
    "code":"hfft"
}

### 获取权限单条数据
POST http://localhost:8000/user.UserAuth/Get
Content-Type: application/json

{
    "name":"admin"
}

### 获取权限列表数据
POST http://localhost:8000/user.UserAuth/List
Content-Type: application/json

{
    "page":1,
    "pageNum":10
}

### 修改单个字段
POST http://localhost:8000/user.UserAuth/Change
Content-Type: application/json

{
    "whereField":"id",
    "whereVal":20,
    "changeField":"sort",
    "changeVal":2
}

### 删除数据
POST http://localhost:8000/user.UserAuth/Del
Content-Type: application/json

{
    "id":1
}